### ISSUE TITLE
传送指令tpa问题

### ISSUE THREAD

**Issue by xiaojuzi122** [cangkuai/ckbase#2]
使用传送指令tpa时，应该是tp到接收人身上，但实际的效果是接收人传送到了请求人身上，是不是反过来了？

**Comment by cangkuai** [comment]
我明天去看看(我真没想到，我写这么垃圾居然有人用)

**Comment by xiaojuzi122** [comment]
加油，另外就是，服务器识别成未知的代码以及不能自动填充的问题什么时候会解决呢

**Comment by xiaojuzi122** [comment]
哦对了，版本是java版1.19.2，有forge

**Comment by cangkuai** [comment]
已修复

**Comment by cangkuai** [comment]
服务器识别成未知的代码目前无解，因为forge官方的指令已经没法用了，我水平又达不到创世神作者那种从头造轮子

**Comment by cangkuai** [comment]
我目前实现指令是通过类似利用一个bug来实现

**Comment by xiaojuzi122** [comment]
好的
